[package]
name = "frozen-collections-core"
description = "Implementation logic for frozen collections."
readme = "README.md"
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ahash = "0.8.11"
hashbrown = "0.15.1"
const-random = "0.1.18"
syn = { version = "2.0.87", features = ["extra-traits", "full"] }
quote = { version = "1.0.37" }
proc-macro2 = { version = "1.0.89" }

[dev-dependencies]
rand = "0.9.0-alpha.1"

[dependencies.bitvec]
version = "1.0.1"
default-features = false
features = ["alloc"]

[features]
default = ["std"]
std = []

[lints]
workspace = true
