[package]
name = "frozen-collections-core"
description = "Implementation logic for frozen collections."
version.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme = "README.md"
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"
hashbrown = "0.15.1"
const-random = "0.1.18"
syn = { version = "2.0.90", features = ["extra-traits", "full"] }
quote = { version = "1.0.37" }
proc-macro2 = { version = "1.0.92" }
mutants = "0.0.3"
equivalent = "1.0.1"

[dev-dependencies]
rand = "0.9.0-beta.1"

[features]
default = ["std"]
std = []

[lints]
workspace = true
