[package]
name = "srcgen"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dev-dependencies]
frozen-collections = { path = "../frozen-collections", features = ["emit"], default-features = false }
syn = { workspace = true }
proc-macro2 = { workspace = true }

[build-dependencies]
frozen-collections = { workspace = true, features = ["emit"] }
syn = { workspace = true }
proc-macro2 = { workspace = true }

[lints]
workspace = true
