[package]
name = "codegen"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
frozen-collections = { workspace = true, features = ["macros", "std"] }
hashbrown = { workspace = true }

[lints]
workspace = true
