[package]
name = "frozen-collections"
description = "Fast partially-immutable collections."
readme.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
resolver = "2"

[dependencies]
ahash = { version = "0.8.11", default-features = false, features = ["default"] }
frozen-collections-macros = { version = "0.2.0", path = "../frozen-collections-macros", optional = true }
frozen-collections-core = { version = "0.2.0", path = "../frozen-collections-core", default-features = false }

[dev-dependencies]
rand = "0.9.0-beta.1"
quote = "1.0.37"
hashbrown = { version = "0.15.2", features = ["serde"] }
criterion = "0.5.1"
boomphf = "0.6.0"
ph = "0.8.5"
frozen-collections-core = { version = "0.2.0", path = "../frozen-collections-core" }
serde = "1.0.216"
serde_json = "1.0.134"

[build-dependencies]
ahash = "0.8.11"
rand = "0.9.0-beta.1"

[[bench]]
name = "string_keys"
harness = false

[[bench]]
name = "scalar_keys"
harness = false

[[bench]]
name = "hashed_keys"
harness = false

[[bench]]
name = "ordered_keys"
harness = false

[[bench]]
name = "perfect_hashing"
harness = false

[lints]
workspace = true

[features]
default = ["std", "macros", "serde"]
serde = ["frozen-collections-core/serde"]
std = ["frozen-collections-core/std"]
macros = ["frozen-collections-macros", "frozen-collections-core/macros"]
