[package]
name = "frozen-collections"
description = "Fast partially-immutable collections."
readme.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ahash = { version = "0.8.11" }
ph = "0.8.5"
rand = "0.9.0-beta.1"

[dev-dependencies]
quote = { version = "1.0.37" }
hashbrown = { version = "0.15.2" }
criterion = "0.5.1"
boomphf = "0.6.0"
ph = "0.8.5"
ptr_hash = "0.1.1"

[build-dependencies]
rand = "0.9.0-beta.1"

[dependencies.frozen-collections-macros]
path = "../frozen-collections-macros"
version = "0.1.0"

[dependencies.frozen-collections-core]
path = "../frozen-collections-core"
default-features = false
version = "0.1.0"

[[bench]]
name = "string_keys"
harness = false

[[bench]]
name = "scalar_keys"
harness = false

[[bench]]
name = "hashed_keys"
harness = false

[[bench]]
name = "ordered_keys"
harness = false

[[bench]]
name = "perfect_hashing"
harness = false

[lints]
workspace = true

[features]
default = ["std"]
std = ["frozen-collections-core/std"]
